# Setup
title:        Standard Container Integration Format
tagline:      ""
baseurl:      "/SCI-F"
paginate:     1
github:       "https://www.github.com/containers-ftw/SCI-F"

# About/contact
author:
  name:       Singularityware
  url:        https://containers-ftw.github.io/apps

# SCI-F Version
version: 0.0.1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

#Others
markdown: kramdown
